name: Auto Run Job Generator

on:
  schedule:
    - cron: '*/50 * * * *'  # Every 50 minutes (UTC time)
  workflow_dispatch:         # Allows manual trigger if needed

jobs:
  run-job-engine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run dummy job engine
      run: python dummy_job_engine.py
